### ISSUE TITLE
 Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry'

### ISSUE THREAD

**Issue by HassHasib** [bharat-1809/glass_kit#14]
im trying to build apk and getting this error,
/C:/src/Pub/Cache/hosted/pub.dev/glass_kit-2.0.1/lib/src/glass_container.dart:406:41: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/border_radius.dart').
      current = ClipRRect(borderRadius: borderRadius, child: current);
                                        ^
Target kernel_snapshot failed: Exception

**Expected behaviour**
/C:/src/Pub/Cache/hosted/pub.dev/glass_kit-2.0.1/lib/src/glass_container.dart:406:41: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/border_radius.dart').
      current = ClipRRect(borderRadius: borderRadius, child: current);
                                        ^
Target kernel_snapshot failed: Exception

**Screenshots**
![glass_kit](https://github.com/bharat-1809/glass_kit/assets/35885144/d23bc524-75de-4da4-890a-3c3ae3e0bc49)

**Flutter:**
 - 3.13.2
 - stable

**Dart:**
 - 3.1.0

**Comment by bharat-1809** [comment]
Hey @HassHasib, thanks for creating an issue.
This will be fixed after the [v3.0.0 release](https://github.com/bharat-1809/glass_kit/releases/tag/v3.0.0). Kindly update the dependency version
