### ISSUE TITLE
Bug when viewing on web

### ISSUE THREAD

**Issue by JayWebtech** [bharat-1809/glass_kit#30]
**Describe the bug**
When viewing my flutter app on web, I have this error:
![image](https://github.com/bharat-1809/glass_kit/assets/45628811/c9b761bf-cb85-44f8-8fb5-2bbd9cf3049b)

But on app, it works fine
I an using the latest version of flutter

**Comment by bharat-1809** [comment]
hey @JayWebtech, as the assertion says, you need to provide a `borderColor` when running the application on the web. For mobile app, it's not required. If your design demands a transparent border you can use `Colors.transparent`

**Comment by JayWebtech** [comment]
Thank you it works
